name: Test Tutorial 2 Greetings
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        working-directory: "greetings"
        run: go get .
      - name: Build
        working-directory: "greetings"
        run: go build -v ./...
      - name: Test greetings
        working-directory: "greetings"
        run: go test